# RalphLoop Pipeline Configuration
# Default pipeline with plan -> execute -> validate stages
#
# This configuration file defines the stages and transitions for the pipeline.
# The framework will load this file automatically if present in the current directory.
#
# Configuration Format:
# - pipeline: Global pipeline settings
# - stages: List of stage definitions
# - transitions: Optional explicit transition rules with conditions
#
# Schema: This file follows the pipeline.schema.json schema.
# For IDE autocompletion and validation, add this comment at the top:
# # yaml-language-server: $schema=pipeline.schema.json
#
# For more information, see: https://github.com/rwese/RalphLoop#pipeline-configuration

# yaml-language-server: $schema=pipeline.schema.json

# =============================================================================
# Pipeline Metadata
# =============================================================================

pipeline:
  name: default
  description: Default RalphLoop pipeline with plan, execute, and validate stages
  max_iterations: 100
  initial_stage: plan

# =============================================================================
# Stage Definitions
# =============================================================================

stages:
  # ---------------------------------------------------------------------------
  # Plan Stage
  # ---------------------------------------------------------------------------
  # Planning stage that analyzes tasks and creates implementation plan
  # Runs before execution to ensure clear direction
  #
  - name: plan
    description: Analyze task and create implementation plan
    entry_command: run_plan_stage
    validation_command: check_plan_complete
    on_success: execute
    on_failure: ""
    timeout: 1800
    ai_validation: false

  # ---------------------------------------------------------------------------
  # Execute Stage
  # ---------------------------------------------------------------------------
  # Primary workload execution stage
  # Runs the main agent loop until work is complete
  #
  - name: execute
    description: Execute the planned implementation
    entry_command: run_execute_stage
    validation_command: check_execution_complete
    on_success: validate
    on_failure: validate
    timeout: 1800
    ai_validation: false

  # ---------------------------------------------------------------------------
  # Validate Stage
  # ---------------------------------------------------------------------------
  # Validation stage that checks if work meets acceptance criteria
  # Can loop back to execute if validation fails
  #
  - name: validate
    description: Validate execution results and quality
    entry_command: run_validate_stage
    validation_command: check_validation_passed
    on_success: ""
    on_failure: execute
    timeout: 600
    ai_validation: false

# =============================================================================
# Transition Rules
# =============================================================================
# Optional explicit transition rules with conditions
# Use this for complex routing logic beyond simple on_success/on_failure
#
# Each transition specifies:
# - from: Source stage name
# - to: Target stage name
# - condition: Bash expression evaluated to determine if transition is allowed
#
# Transitions are checked in order - first matching transition is used
# If no transitions match, the on_success/on_failure from stage definition is used
#
# Example transitions (uncomment and customize as needed):
# transitions:
#   - from: execute
#     to: complete
#     condition: "[[ $RALPH_PIPELINE_FAST_MODE == true ]]"
#   - from: execute
#     to: execute
#     condition: "[[ $PIPELINE_CURRENT_ITERATION -lt 3 ]]"
#
# transitions: []

# =============================================================================
# Stage Commands Reference
# =============================================================================
#
# The following built-in commands are available:
#
# Built-in Commands:
#   run_plan_stage         - Analyze task and create implementation plan
#   run_execute_stage      - Execute the planned implementation
#   run_validate_stage     - Validate results and quality
#
# Validation Functions:
#   check_plan_complete        - Check if planning is complete
#   check_execution_complete   - Check if work is complete
#   check_validation_passed    - Check if validation passed
#
# Custom Commands:
#   You can specify any bash command or script as entry_command
#   or validation_command
#
# Examples:
#   entry_command: "./scripts/my-script.sh"
#   entry_command: "npm run build"
#   validation_command: "[[ -f build/output.txt ]] && grep -q SUCCESS build/output.txt"
#
# =============================================================================
# AI Integration
# =============================================================================
#
# To enable AI-enhanced validation for a stage, set:
#   ai_validation: true
#
# This will trigger AI validation hooks that can make decisions
# about stage transitions based on context and goals.
#
# AI validation is controlled by the following environment variables:
#   RALPH_PIPELINE_AI_ENABLED    - Enable AI features (default: false)
#   RALPH_AGENT_VALIDATION       - Agent to use for validation
#
# Note: AI validation is optional and does not break bash-only workflows
#
# =============================================================================
# Timeout Configuration
# =============================================================================
#
# Stage timeouts are specified in seconds:
#   timeout: 1800    # 30 minutes
#   timeout: 300     # 5 minutes
#   timeout: 0       # No timeout (use with caution)
#
# If a stage times out, the pipeline treats it as a failure
# and follows the on_failure transition path.
#
# =============================================================================
# Examples
# =============================================================================
#
# For more complex pipeline examples, see:
#   examples/pipeline/ci-cd.yaml
#   examples/pipeline/iterative-refactor.yaml
#   examples/pipeline/quick-prototype.yaml
#
